
services:
  auth-service:
    build: ./authService
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo

  battery-passport-service:
    build: ./batteryPassportService
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    depends_on:
      - mongo
      - kafka

  document-service:
    build: ./documentService
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
    depends_on:
      - mongo
      - kafka
      - s3

  notification-service:
    build: ./notificationService
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
    depends_on:
      - kafka

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - s3data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  s3data: